[features]
seeds = false
skip-lint = false
[programs.localnet]
bestlend = "9iUmehkCkXHmatHiRjKpXTsPDxNCLMfmtSzhJKm5h94z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sc4recoin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
